# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 54333
      dbname: postgres
      schema: dbt_hsdanield
      threads: 4